# Generated by Django 4.0.6 on 2022-07-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anasayfa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cover',
            name='title',
            field=models.CharField(help_text='Anasayfa', max_length=100, verbose_name='Başlık'),
        ),
    ]
