# Generated by Django 4.0.6 on 2022-07-10 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anasayfa', '0002_alter_cover_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cover',
            name='image',
            field=models.ImageField(blank=True, upload_to='home/cover/', verbose_name='Anasayfa Kapak'),
        ),
    ]
