# Generated by Django 4.0.6 on 2022-07-10 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anasayfa', '0003_alter_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cover',
            name='theme',
            field=models.CharField(choices=[('', '------'), ('dark', 'SİYAH'), ('primary', 'PEMBE'), ('danger', 'KIRMIZI'), ('info', 'MAVİ')], default='', max_length=100, verbose_name='Tema'),
        ),
    ]
