# Generated by Django 4.0.6 on 2022-07-10 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anasayfa', '0004_cover_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cover',
            name='theme',
            field=models.CharField(blank=True, choices=[('', '------'), ('dark', 'Siyah'), ('primary', 'Pembe'), ('danger', 'Kırmızı'), ('info', 'Mavi'), ('success', 'Yaşil')], default='', help_text='Kapak Fotoğrafı seçtiyseniz seçin', max_length=100, verbose_name='Tema'),
        ),
    ]
